### ISSUE TITLE
Error: EACCES: permission denied, scandir '/' [shared hosting user installation]

### ISSUE THREAD

**Issue by alienfromouterspace** [barsh/true-case-path#2]
I'm using shared hosting, so I don't have access to anything outside my home folder.
Is it possible to fix this issue, without accessing anything outside home folder?
```
/usr/home/spider/hello_phoenix/node_modules/true-case-path/node_modules/glob/sync.js:321

        throw er

        ^

​

Error: EACCES: permission denied, scandir '/'

  at Object.fs.readdirSync (fs.js:914:18)

  at GlobSync._readdir (/usr/home/spider/hello_phoenix/node_modules/true-case-path/node_modules/glob/sync.js:275:41)

  at GlobSync._processReaddir (/usr/home/spider/hello_phoenix/node_modules/true-case-path/node_modules/glob/sync.js:135:22)

  at GlobSync._process (/usr/home/spider/hello_phoenix/node_modules/true-case-path/node_modules/glob/sync.js:130:10)

  at new GlobSync (/usr/home/spider/hello_phoenix/node_modules/true-case-path/node_modules/glob/sync.js:46:10)

  at Function.globSync [as sync] (/usr/home/spider/hello_phoenix/node_modules/true-case-path/node_modules/glob/sync.js:24:10)

  at trueCasePathSync (/usr/home/spider/hello_phoenix/node_modules/true-case-path/index.js:29:15)

  at trueCasePath 


```

**Comment by caseyWebb** [comment]
Workaround provided fork Profiscience/true-case-path, published in 2.2.1.

Use `baseUrl` argument; see docs.
